#!/bin/bash
#SBATCH --time=1:30:00 # days-hh:mm:ss
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=2625 # megabytes
#SBATCH --partition=bio
#SBATCH --output=slurm-%j.out
#SBATCH --open-mode=append


module --ignore-cache load Nextflow/21.08.0

nextflow run main.nf \
 --data='./data/illumina/05757/2010_test/' --metadata='./data/metadata/05757_2010_test.tsv' \
 --reference='./data/references/05757_1991_polca.fasta' --outdir='Aciculoconiduim_05757_2010_merged_bam' \
 --cpus=20 --merged_vcf  -resume






#nextflow run main.nf --data='./data/illumina_2025-04-28/05757/1991' --metadata='./data/metadata/05757_1991.tsv' --reference='./data/references/IHEM_05757_LN1991_1_reference_assembly.fasta' \
#--outdir='Aciculoconiduim_05757_1991_merged_new_parall' --cpus=40 --merged 

#nextflow run main.nf --data='./data/illumina_2025-04-28/05757/1991' --metadata='./data/metadata/05757_1991.tsv' --reference='./data/references/IHEM_05757_LN1991_1_reference_assembly.fasta' \
#--outdir='Aciculoconiduim_05757_1991_not_merged' --cpus=40

#nextflow run main.nf --data='./data/illumina_2025-04-28/05757/2010' --metadata='./data/metadata/05757_2010.tsv' --reference='./data/references/IHEM_05757_LN1991_1_reference_assembly.fasta' \
#--outdir='Aciculoconiduim_05757_2010_merged' --cpus=40 --merged 

#nextflow run main.nf --data='./data/illumina_2025-04-28/05757/2010' --metadata='./data/metadata/05757_2010.tsv' --reference='./data/references/IHEM_05757_LN1991_1_reference_assembly.fasta' \
#--outdir='Aciculoconiduim_05757_2010_not_merged' --cpus=40



#nextflow run main.nf --data='./data/data-1996' --metadata='./data/metadata_1996.tsv' --reference='./data/IHEM_04380_LY1996_0339_1_reference_assembly.fasta' \
#--outdir='output_1996_merged' --cpus=40 --merged 

#nextflow run main.nf --data='./data/data-1996' --metadata='./data/metadata_1996.tsv' --reference='./data/IHEM_04380_LY1996_0339_1_reference_assembly.fasta' \
#--outdir='output_1996_not_merged_bcf' --cpus=40




#nextflow run main.nf --data='./data/illumina_2025-04-28/04380/1996/' --metadata='./data/metadata/04380_1996.tsv' --reference='./data/references/04380_1996.fasta' \
#--outdir='Aspergillus_04380_1996_merged_vcf' --cpus=20   --merged_vcf
#nextflow run main.nf --data='./data/illumina_2025-04-28/04380/1996' --metadata='./data/metadata/04380_1996.tsv' --reference='./data/references/04380_1996_masurca.fasta' \
#--outdir='Aspergillus_04380_1996_merged_vcf_masurca' --cpus=20 --merged_vcf
#nextflow run main.nf --data='./data/illumina_2025-04-28/04380/1996' --metadata='./data/metadata/04380_1996.tsv' --reference='./data/references/04380_1996_masurca.fasta' \
#--outdir='Aspergillus_04380_1996_masurca' --cpus=20 -resume


#nextflow run main.nf --data='./data/illumina_2025-04-28/05757/1991' --metadata='./data/metadata/05757_1991.tsv' --reference='./data/references/05757_1991_polca.fasta' \
#--outdir='Aciculoconiduim_05757_1991_merged_vcf_polca' --cpus=20  --merged_vcf

#nextflow run main.nf --data='./data/illumina_2025-04-28/05658/1999' --metadata='./data/metadata/05658_1999.tsv' --reference='./data/references/05658_1999_polca.fasta' \
#--outdir='Trichoderma_05658_1999_merged_bam_polca' --cpus=8 --merged_bam

